"""Runtime-neutral contracts with no product runtime socket access."""

from .errors import ErrorCode, RetryDisposition, RuntimeBackendError, RuntimePhase
from .fencing import RuntimeFencingContext
from .models import (
    ArtifactRecord,
    ContainerHandle,
    InputFile,
    JobIdentity,
    JobKind,
    ManagedObjects,
    RawArtifactArchive,
    ResourceLimits,
    RunResult,
    RuntimeCapabilities,
    RuntimeHealth,
    RuntimeKind,
    RuntimeProbe,
    SandboxSpec,
    TerminalClassification,
    TerminationReason,
    ValidatedArtifactArchive,
    ValidatedInputArchive,
    ValidatedSandboxSpec,
    VolumeHandle,
)
from .policy import EngineProfile, SandboxPolicy
from .protocol import RuntimeBackend, RuntimeJobBackend

__all__ = [
    "ArtifactRecord",
    "ContainerHandle",
    "EngineProfile",
    "ErrorCode",
    "InputFile",
    "JobIdentity",
    "JobKind",
    "ManagedObjects",
    "RawArtifactArchive",
    "ResourceLimits",
    "RetryDisposition",
    "RunResult",
    "RuntimeBackend",
    "RuntimeFencingContext",
    "RuntimeJobBackend",
    "RuntimeBackendError",
    "RuntimeCapabilities",
    "RuntimeHealth",
    "RuntimeKind",
    "RuntimePhase",
    "RuntimeProbe",
    "SandboxPolicy",
    "SandboxSpec",
    "TerminalClassification",
    "TerminationReason",
    "ValidatedArtifactArchive",
    "ValidatedInputArchive",
    "ValidatedSandboxSpec",
    "VolumeHandle",
]
