"""Runtime-neutral contracts with no product runtime socket access."""

from .errors import ErrorCode, RetryDisposition, RuntimeBackendError, RuntimePhase
from .fence_authority import (
    InMemoryRuntimeFenceAuthority,
    RUNTIME_FENCE_AUTHORITY_PRODUCT_ENABLED,
    RuntimeFenceAuthority,
)
from .fencing import (
    RUNTIME_FENCE_LABEL_KEYS,
    RUNTIME_FENCING_TOKEN_LABEL,
    RUNTIME_JOB_ID_LABEL,
    RUNTIME_OWNER_ID_LABEL,
    TAKEOVER_OBJECT_PHASES,
    RuntimeFencingContext,
    enforce_runtime_object_fence,
)
from .models import (
    ArtifactRecord,
    ContainerHandle,
    InputFile,
    JobIdentity,
    JobKind,
    ManagedObjects,
    RawArtifactArchive,
    ResourceLimits,
    RunResult,
    RuntimeCapabilities,
    RuntimeHealth,
    RuntimeKind,
    RuntimeProbe,
    SandboxSpec,
    TerminalClassification,
    TerminationReason,
    ValidatedArtifactArchive,
    ValidatedInputArchive,
    ValidatedSandboxSpec,
    VolumeHandle,
)
from .policy import EngineProfile, SandboxPolicy
from .protocol import RuntimeBackend, RuntimeJobBackend

__all__ = [
    "ArtifactRecord",
    "ContainerHandle",
    "EngineProfile",
    "ErrorCode",
    "InMemoryRuntimeFenceAuthority",
    "InputFile",
    "JobIdentity",
    "JobKind",
    "ManagedObjects",
    "RawArtifactArchive",
    "ResourceLimits",
    "RUNTIME_FENCE_AUTHORITY_PRODUCT_ENABLED",
    "RUNTIME_FENCE_LABEL_KEYS",
    "RUNTIME_FENCING_TOKEN_LABEL",
    "RUNTIME_JOB_ID_LABEL",
    "RUNTIME_OWNER_ID_LABEL",
    "RetryDisposition",
    "RunResult",
    "RuntimeBackend",
    "RuntimeFenceAuthority",
    "RuntimeFencingContext",
    "RuntimeJobBackend",
    "RuntimeBackendError",
    "RuntimeCapabilities",
    "RuntimeHealth",
    "RuntimeKind",
    "RuntimePhase",
    "RuntimeProbe",
    "SandboxPolicy",
    "SandboxSpec",
    "TAKEOVER_OBJECT_PHASES",
    "TerminalClassification",
    "TerminationReason",
    "ValidatedArtifactArchive",
    "ValidatedInputArchive",
    "ValidatedSandboxSpec",
    "VolumeHandle",
    "enforce_runtime_object_fence",
]
