"""Engine-independent broker library with no service transport or runtime socket."""

from .archive import (
    ArchiveLimits,
    InputPayload,
    build_canonical_input_archive,
    validate_canonical_input_archive,
)
from .cancellation import CancellationOutcome, CancellationRequest
from .cancellation_arbitration import (
    DurableCancellationCheckpoint,
    DurableCancellationCrashInjection,
    DurableCancellationCrashSignal,
    DurableCancellationInterrupted,
)
from .cleanup import JobCleanupCoordinator
from .diagnostics import InternalDiagnostic
from .lease import (
    DEFAULT_OWNER_HEARTBEAT_INTERVAL_MS,
    DEFAULT_OWNER_LEASE_DURATION_MS,
    MAX_OWNER_LEASE_DURATION_MS,
    LeaseClock,
    OwnerLeasePolicy,
    SystemLeaseClock,
)
from .lifecycle import CancellationSignal, LifecycleCheckpoint, PhaseCancellation
from .live_state import LiveStateEmission, LiveStateSession, LiveStateWriteError
from .models import (
    BrokerError,
    BrokerEvent,
    BrokerOutcome,
    BrokerRequest,
    BrokerState,
    ReconciliationReport,
)
from .orchestrator import SandboxBroker
from .output_archive import (
    ArtifactPayload,
    build_canonical_output_archive,
    output_archive_limits,
    validate_canonical_output_archive,
)
from .recovery import (
    CrashRecoveryCoordinator,
    RecoveryCheckpoint,
    RecoveryCrashInjection,
    RecoveryCrashSignal,
    RecoveryInterrupted,
    RecoveryItem,
    RecoveryReconciler,
    RecoveryReport,
    RecoveryRequest,
    RecoveryStatus,
)
from .runtime_fence_activation import (
    RUNTIME_FENCE_ACTIVATION_PRODUCT_ENABLED,
    DurableRuntimeFenceActivator,
)
from .state import (
    DurableJobEvent,
    DurableJobStateStore,
    DurableOperationGuard,
    DurableOperationOwnership,
    InMemoryJobStateStore,
    InMemoryStateStoreBacking,
    JobStateSnapshot,
    OperationFenceActivator,
    OperationOwnershipError,
    OperationOwnershipGuard,
    RecoverableStatePage,
    StateStoreError,
    StateStoreErrorCode,
    validate_state_transition,
)
from .sqlite_state import (
    SQLITE_STATE_PRODUCT_ENABLED,
    SQLITE_STATE_RETENTION_POLICY,
    SQLITE_STATE_SCHEMA_VERSION,
    SQLiteJobStateStore,
)
from .state_composition import (
    BROKER_STATE_COMPOSITION_PRODUCT_ENABLED,
    BrokerStartupReport,
    BrokerStartupRequest,
    DurableBrokerComposition,
    StateCompositionError,
    StateCompositionErrorCode,
    StateOperationContext,
)
from .state_mapping import (
    BrokerStateMapper,
    MappedStateBatch,
    StateEventRecorder,
    StateMappingContext,
    StateMappingError,
    StateMappingErrorCode,
)

__all__ = [
    "ArchiveLimits",
    "ArtifactPayload",
    "BrokerError",
    "BrokerEvent",
    "BrokerOutcome",
    "BrokerRequest",
    "BROKER_STATE_COMPOSITION_PRODUCT_ENABLED",
    "BrokerStartupReport",
    "BrokerStartupRequest",
    "BrokerState",
    "BrokerStateMapper",
    "CancellationOutcome",
    "CancellationRequest",
    "CancellationSignal",
    "CrashRecoveryCoordinator",
    "DurableCancellationCheckpoint",
    "DurableCancellationCrashInjection",
    "DurableCancellationCrashSignal",
    "DurableCancellationInterrupted",
    "DurableJobEvent",
    "DurableBrokerComposition",
    "DurableJobStateStore",
    "DurableOperationGuard",
    "DurableOperationOwnership",
    "DurableRuntimeFenceActivator",
    "DEFAULT_OWNER_HEARTBEAT_INTERVAL_MS",
    "DEFAULT_OWNER_LEASE_DURATION_MS",
    "InMemoryJobStateStore",
    "InMemoryStateStoreBacking",
    "InputPayload",
    "InternalDiagnostic",
    "JobCleanupCoordinator",
    "JobStateSnapshot",
    "LeaseClock",
    "LifecycleCheckpoint",
    "LiveStateEmission",
    "LiveStateSession",
    "LiveStateWriteError",
    "MAX_OWNER_LEASE_DURATION_MS",
    "MappedStateBatch",
    "OperationFenceActivator",
    "OperationOwnershipError",
    "OperationOwnershipGuard",
    "OwnerLeasePolicy",
    "PhaseCancellation",
    "RecoverableStatePage",
    "ReconciliationReport",
    "RecoveryCheckpoint",
    "RecoveryCrashInjection",
    "RecoveryCrashSignal",
    "RecoveryInterrupted",
    "RecoveryItem",
    "RecoveryReconciler",
    "RecoveryReport",
    "RecoveryRequest",
    "RecoveryStatus",
    "RUNTIME_FENCE_ACTIVATION_PRODUCT_ENABLED",
    "SQLITE_STATE_PRODUCT_ENABLED",
    "SQLITE_STATE_RETENTION_POLICY",
    "SQLITE_STATE_SCHEMA_VERSION",
    "SQLiteJobStateStore",
    "SandboxBroker",
    "StateCompositionError",
    "StateCompositionErrorCode",
    "StateEventRecorder",
    "StateMappingContext",
    "StateMappingError",
    "StateMappingErrorCode",
    "StateStoreError",
    "StateOperationContext",
    "StateStoreErrorCode",
    "SystemLeaseClock",
    "build_canonical_input_archive",
    "build_canonical_output_archive",
    "output_archive_limits",
    "validate_canonical_input_archive",
    "validate_canonical_output_archive",
    "validate_state_transition",
]
