export const mvpEn = {
  title: "Device laboratory", subtitle: "Change inputs. Inspect calculated curves. Run a local numerical solve.",
  calculator: "Instant NMOS calculator", model: "Long-channel square-law model · 300 K",
  limits: "Educational approximation: constant mobility, strong inversion, ideal oxide; no subthreshold current, channel-length modulation, quantum or short-channel effects. Not DEVSIM or process simulation.",
  lengthUm: "Channel length L (μm)", widthUm: "Channel width W (μm)", oxideNm: "Oxide thickness (nm)",
  dopingCm3: "Body acceptors (cm⁻³)", mobilityCm2Vs: "Electron mobility (cm²/V·s)", flatbandV: "Flat-band voltage (V)",
  gateV: "Gate-source VGS (V)", drainV: "Drain-source VDS (V)", bodyV: "Source-body VSB (V)",
  cutoff: "Cutoff", linear: "Linear region", saturation: "Saturation", invalid: "Enter finite values within the displayed limits. No result is calculated for invalid inputs.",
  threshold: "Threshold voltage", current: "Drain current", output: "Output characteristic", transfer: "Transfer characteristic",
  drawing: "Parameter-driven NMOS schematic", schematic: "Schematic, not a solved mesh. Oxide thickness is exaggerated; width is out of plane.",
  save: "Save inputs and results", open: "Load calculation inputs", replace: "Replace current calculation?", discard: "Discard", apply: "Apply inputs",
  fileHelp: "Save before reloading. Loading a record recomputes its inputs; stored results are not trusted.", fileError: "Unsupported or invalid calculation file.",
  samples: "Numerical samples", voltage: "Voltage (V)", currentMa: "Current (mA)", restored: "Inputs loaded and recalculated",
  solver: "Local DEVSIM laboratory", localHelp: "A separate, opt-in local service runs fixed templates only. It does not activate the M3 product or execute process decks.",
  unavailable: "Start the experimental local service to use DEVSIM. Browser calculations work without it.",
};
export const mvpKo: Record<keyof typeof mvpEn, string> = {
  title: "소자 실험실", subtitle: "입력을 바꾸고 계산된 곡선을 확인하거나 로컬 수치 해석을 실행하세요.",
  calculator: "즉시 계산 NMOS 계산기", model: "장채널 제곱 법칙 모델 · 300 K",
  limits: "교육용 근사 모델: 일정한 이동도, 강한 반전, 이상적인 산화막을 가정합니다. 문턱 아래 전류, 채널 길이 변조, 양자 및 단채널 효과는 제외합니다. DEVSIM이나 공정 시뮬레이션이 아닙니다.",
  lengthUm: "채널 길이 L (μm)", widthUm: "채널 폭 W (μm)", oxideNm: "산화막 두께 (nm)",
  dopingCm3: "기판 억셉터 농도 (cm⁻³)", mobilityCm2Vs: "전자 이동도 (cm²/V·s)", flatbandV: "평탄 밴드 전압 (V)",
  gateV: "게이트-소스 VGS (V)", drainV: "드레인-소스 VDS (V)", bodyV: "소스-기판 VSB (V)",
  cutoff: "차단", linear: "선형 영역", saturation: "포화 영역", invalid: "표시된 범위 내 유한한 값을 입력하세요. 잘못된 입력으로 결과를 계산하지 않습니다.",
  threshold: "문턱 전압", current: "드레인 전류", output: "출력 특성", transfer: "전달 특성",
  drawing: "파라미터 기반 NMOS 개략도", schematic: "해석 메시가 아닌 개략도입니다. 산화막 두께는 확대 표시하며 폭은 화면에 수직인 방향입니다.",
  save: "입력과 결과 저장", open: "계산 입력 불러오기", replace: "현재 계산 입력을 교체할까요?", discard: "취소", apply: "입력 적용",
  fileHelp: "새로고침 전에 저장하세요. 파일을 불러오면 입력으로 다시 계산하며 저장된 결과를 신뢰하지 않습니다.", fileError: "지원하지 않거나 잘못된 계산 파일입니다.",
  samples: "수치 표본", voltage: "전압 (V)", currentMa: "전류 (mA)", restored: "입력을 불러와 다시 계산했습니다",
  solver: "로컬 DEVSIM 실험실", localHelp: "별도로 선택해 시작하는 로컬 서비스가 고정 템플릿만 실행합니다. M3 제품 활성화나 공정 덱 실행은 수행하지 않습니다.",
  unavailable: "DEVSIM을 사용하려면 실험용 로컬 서비스를 시작하세요. 브라우저 계산은 독립적으로 동작합니다.",
};
